In [119]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.utils import to_categorical
from keras.preprocessing import image
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
from tqdm import tqdm


In [120]:
train = pd.read_csv('train_ids_labels.csv')


In [121]:
# We have grayscale images, so while loading the images we will keep grayscale=True, if you have RGB images, you should set grayscale as False
train_image = []
for i in tqdm(range(train.shape[0])):
    img = image.load_img(train['Image_ID'][i]+'.JPG', target_size=(28,28,1), grayscale=False)
    img = image.img_to_array(img)
    img = img/255
    train_image.append(img)
X = np.array(train_image)


 72%|███████▏  | 2910/4026 [00:32<00:11, 94.54it/s]


100%|██████████| 4026/4026 [00:44<00:00, 90.91it/s]

In [122]:
y = train['Label']

In [123]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2)

In [124]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),activation='relu',input_shape=(28,28,1)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

In [125]:
from keras.applications.vgg16 import VGG16

In [81]:
mod = VGG16()

In [126]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),activation='relu',input_shape=(28,28,3)))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(2, activation='softmax'))

In [127]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [128]:
model.fit(X_train, y_train, epochs=10)

Epoch 1/10
3220/3220 [==============================] - 7s 2ms/step - loss: 0.4589 - acc: 0.7870
Epoch 2/10
3220/3220 [==============================] - 7s 2ms/step - loss: 0.3132 - acc: 0.8618
Epoch 3/10
3220/3220 [==============================] - 7s 2ms/step - loss: 0.2594 - acc: 0.8910
Epoch 4/10
3220/3220 [==============================] - 7s 2ms/step - loss: 0.2341 - acc: 0.8994
Epoch 5/10
3220/3220 [==============================] - 7s 2ms/step - loss: 0.2005 - acc: 0.9168
Epoch 6/10
3220/3220 [==============================] - 8s 3ms/step - loss: 0.1740 - acc: 0.9326
Epoch 7/10
3220/3220 [==============================] - 7s 2ms/step - loss: 0.1482 - acc: 0.9407
Epoch 8/10
3220/3220 [==============================] - 7s 2ms/step - loss: 0.1458 - acc: 0.9422
Epoch 9/10
3220/3220 [==============================] - 7s 2ms/step - loss: 0.1208 - acc: 0.9559
Epoch 10/10
3220/3220 [==============================] - 7s 2ms/step - loss: 0.1264 - acc: 0.9506


In [129]:
y_score = model.predict_proba(X_test)

In [130]:
print(y_score)

[[9.8533183e-01 1.4668099e-02]
 [9.9933630e-01 6.6371378e-04]
 [5.9054631e-01 4.0945363e-01]
 ...
 [7.5465256e-01 2.4534738e-01]
 [3.3280409e-03 9.9667192e-01]
 [7.4173373e-01 2.5826630e-01]]


In [131]:
test = pd.read_csv('test_ids_only.csv')

In [132]:
print(test.shape)

(1650, 1)


In [133]:
# We have grayscale images, so while loading the images we will keep grayscale=True, if you have RGB images, you should set grayscale as False
train_image = []
for i in tqdm(range(test.shape[0])):
    img = image.load_img(test['Image_ID'][i]+'.JPG', target_size=(28,28,1), grayscale=False)
    img = image.img_to_array(img)
    img = img/255
    train_image.append(img)
Test = np.array(train_image)


100%|██████████| 1650/1650 [00:17<00:00, 93.27it/s]

In [134]:
print(Test.shape)

(1650, 28, 28, 3)


In [114]:
#sample_submission = model.predict_proba(Test)

In [115]:
#print(sample_submission)

[[7.6203257e-02 9.2379671e-01]
 [8.8383585e-01 1.1616410e-01]
 [1.0000000e+00 6.1007527e-12]
 ...
 [9.0063751e-01 9.9362478e-02]
 [4.7425899e-01 5.2574092e-01]
 [6.5132803e-01 3.4867197e-01]]


In [116]:
#np.savetxt("sample.csv",sample_submission,delimiter = ",")

In [159]:
sample_submission = model.predict_proba(Test).clip(0.1,0.3)

In [160]:
print(sample_submission)

[[0.3        0.20631401]
 [0.3        0.1       ]
 [0.3        0.1       ]
 ...
 [0.3        0.3       ]
 [0.26808572 0.3       ]
 [0.3        0.14578497]]


In [161]:
np.savetxt("sample.csv",sample_submission,delimiter = ",")
